### ISSUE TITLE
Unpinned versions of Pandera breaks some code

### ISSUE THREAD

**Issue by staylorx** [UCBoulder/cupyopt#16]
An implied upgrade to the latest pandera version (0.5.0, specifically) doesn't include the io modules in the __init__. We've mostly moved off this line of validation but we should use == pinning or even ~= to ensure we don't jump up a breaking level (viz., 0.4.4 to 0.5.0).

**Comment by staylorx** [comment]
@d33bs, I recommend removing Pandera entirely.

**Comment by d33bs** [comment]
Removing Pandera as a dependency sounds like a good plan. By using Avro schema and existing cupyopt functions we can be somewhat assured of validation capabilities should they be desired after Pandera is removed. I plan to address this issue in a new branch.

**Comment by d33bs** [comment]
Resolved by #17 & #18
